# Generated by Django 5.1 on 2024-08-27 10:36

import distributionApp.models
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Vehicle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vehicle_name', models.CharField(max_length=20)),
                ('weight_capacity', models.FloatField()),
                ('size_capacity', models.IntegerField()),
                ('vehicle_type', models.CharField(choices=[('cold', 'Cold'), ('normal', 'Normal')], max_length=6)),
                ('area', models.CharField(choices=[('area1', 'Area 1'), ('area2', 'Area 2'), ('area3', 'Area 3')], max_length=10)),
            ],
            bases=(models.Model, distributionApp.models.TypeNormalizationMixin),
        ),
        migrations.CreateModel(
            name='Package',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('package_name', models.CharField(max_length=20)),
                ('weight', models.FloatField()),
                ('size', models.FloatField()),
                ('package_type', models.CharField(choices=[('cold', 'Cold'), ('normal', 'Normal')], max_length=6)),
                ('package_location', models.CharField(max_length=1000)),
                ('vehicle', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='packages', to='distributionApp.vehicle')),
            ],
            bases=(models.Model, distributionApp.models.TypeNormalizationMixin),
        ),
    ]
