# Generated by Django 5.1 on 2024-08-27 19:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('distributionApp', '0002_remove_vehicle_area_area'),
    ]

    operations = [
        migrations.CreateModel(
            name='AreaPackageAssignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('area', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='area_assignments', to='distributionApp.area')),
                ('package', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='area_assignments', to='distributionApp.package')),
                ('vehicle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='area_assignments', to='distributionApp.vehicle')),
            ],
        ),
    ]
