# Generated by Django 5.1 on 2024-08-28 10:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('distributionApp', '0003_areapackageassignment'),
    ]

    operations = [
        migrations.AddField(
            model_name='package',
            name='is_delivered',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='vehicle',
            name='km_capacity',
            field=models.FloatField(default=100),
            preserve_default=False,
        ),
    ]
