# Generated by Django 5.1 on 2024-08-31 18:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('distributionApp', '0004_package_is_delivered_vehicle_km_capacity'),
    ]

    operations = [
        migrations.CreateModel(
            name='TemporaryPackageAssignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('area', models.CharField(choices=[('area1', 'Area 1'), ('area2', 'Area 2'), ('area3', 'Area 3')], max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('package', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='distributionApp.package')),
            ],
        ),
    ]
