# Generated by Django 5.1 on 2024-09-01 11:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('distributionApp', '0005_temporarypackageassignment'),
    ]

    operations = [
        migrations.CreateModel(
            name='TemporarySelection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('package', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='temporary_selections', to='distributionApp.package')),
                ('vehicle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='temporary_selections', to='distributionApp.vehicle')),
            ],
        ),
    ]
